linters:
  enable-all: true
  disable:
    ### deprecated, archived or obsolette by authors
    - paralleltest
    - deadcode
    - ifshort
    - interfacer
    - golint
    - maligned
    - scopelint
    - structcheck
    - exhaustivestruct
    - nosnakecase
    - varcheck
    ### disabled by me
    - gofumpt
    - depguard
    # - varnamelen
    # - tagliatelle
    # - gosmopolitan
    # - forbidigo
    # - godot
    - exhaustruct
linters-settings:
  gosec:
    excludes:
      - G114
issues:
  exclude-rules:
    # - path: internal/interfaces/testdb
    #   linters:
    #     - gomnd
    #     - gochecknoglobals
    - path: _test.go$
      linters:
        - gochecknoglobals
    # - linters:
    #   - revive
    #   text: "blank-imports"
