linters:
  enable-all: true
  disable:
    ### deprecated, archived or obsolette by authors
    - deadcode
    - exhaustivestruct
    - gci
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - varcheck
    ### disabled by me
    # - forbidigo
    # - godot
    # - gosmopolitan
    # - tagliatelle
    # - varnamelen
    - depguard
    - exhaustruct
    - godox
    - gofumpt
linters-settings:
  gosec:
    excludes:
      - G114
issues:
  exclude-rules:
    # - path: internal/interfaces/testdb
    #   linters:
    #     - gomnd
    #     - gochecknoglobals
    - path: _test.go$
      linters:
        - gochecknoglobals
        - goerr113
    - linters:
      - varnamelen
      text: "parameter name 'w' is too short for the scope of its usage"
    - linters:
      - revive
      text: "blank-imports"
