# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'debug'
gem 'factory_bot'
gem 'faker'
gem 'faraday'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
